<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>call_center</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9e0ea3b0-45ef-4d7d-90f7-df6ac1c7e301</testSuiteGuid>
   <testCaseLink>
      <guid>631ef448-8262-4c87-83e1-7158a143b54e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call_Center/Create_New_Student</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ed4fa0c-82f1-4874-8fbe-21e6451c08c5</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/username/username</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7ed4fa0c-82f1-4874-8fbe-21e6451c08c5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>姓名</value>
         <variableId>cfc644c9-3ded-402e-98ea-61671c7446bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ed4fa0c-82f1-4874-8fbe-21e6451c08c5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>性别</value>
         <variableId>61a5c599-df15-42df-bfa2-df488226f5ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ed4fa0c-82f1-4874-8fbe-21e6451c08c5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>出生日期</value>
         <variableId>d6aa079a-6fba-4b55-84fb-78f7964f30e9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
