<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>raido_girl</name>
   <tag></tag>
   <elementGuidId>7d018e12-9463-43e6-941d-654472e05340</elementGuidId>
   <imagePath>C:\Users\kuu\Katalon Studio\call_center\Object Repository\CallCenter\CreateNewStudent\images\female.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='男'])[6]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ivu-radio-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ivuRadioGroup_1566785675491_3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;modal-height1 v-transfer-dom&quot;]/div[@class=&quot;ivu-modal-wrap&quot;]/div[@class=&quot;ivu-modal&quot;]/div[@class=&quot;ivu-modal-content&quot;]/div[@class=&quot;ivu-modal-body&quot;]/form[@class=&quot;ivu-form ivu-form-label-right&quot;]/div[@class=&quot;ivu-row&quot;]/div[@class=&quot;ivu-col ivu-col-span-10&quot;]/div[@class=&quot;ivu-form-item ivu-form-item-required&quot;]/div[@class=&quot;ivu-form-item-content&quot;]/div[@class=&quot;ivu-radio-group ivu-radio-group-default ivu-radio-default&quot;]/label[@class=&quot;ivu-radio-wrapper ivu-radio-group-item ivu-radio-wrapper-checked ivu-radio-default&quot;]/span[@class=&quot;ivu-radio ivu-radio-checked&quot;]/input[@class=&quot;ivu-radio-input&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CallCenter/CreateNewStudent/Page_Create_New_Student/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='ivuRadioGroup_1566785675491_3'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='男'])[6]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所在城市'])[2]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='年部'])[2]/preceding::input[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/label[2]/span/input</value>
   </webElementXpaths>
</WebElementEntity>
